# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swf-Keychain-demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swf-Keychain-demo
  pod 'KeychainAccess'

  target 'swf-Keychain-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
